@startuml
'header SayHello
'footer Page %page% of %lastpage%

skinparam component {
    backgroundColor [Biblio] LightGray
}


package "Klienter/brugergrænseflader" {
 together {
    package "Borgere" {
      [Bibliotek.dk]
      [Biblio] #LightGray
      [Bibzoom] #LightGray
      [FFU portaler]
      [Brugerportalsinitiativet] #LightGray
      [DDB CMS] #Cyan
      [Filmstriben]
      [FBS Skoleportl]
      [eReolen] #Cyan
      [Arthesis]
      [Faktorlink]
      [Forfatterweb]
      [Litteratursiden] #Cyan
      [Filmcentralen]
      [Nota]
      [Biblioteksvagten] #Cyan
      [Borger.dk]
      [Finurlige Fakta]
      [Biblioteket App] #Cyan
    }
    
    package "Personale" {
      [ERMS] #Cyan
      [FAKTOR] #Cyan
      [Biblioteksvagten] #Cyan
      [FFU CMS]
      [VIP]
      [Netpunkt]
      [Bob]
      [OpenSource DBC]
      [Open Cataloguing]
      [FBS Admin]
    }
}
}
@enduml
