@startuml
'header SayHello
'footer Page %page% of %lastpage%

skinparam component {
    backgroundColor [Biblio] LightGray
}

package "Dataplatforme" {

    package "Metadata" {
        [Databrønd]
        [Viden DB]
        [Forsider]
        [WorldCat]
        [FFU Databrønde]
        [OpenList]
        [ADHL] #LightGray
        [VoxB] #LightGray
        [BPI (Inlead)] #Cyan
        [Personalisering]
    }
    
    package "Administrative data" {
        [BOB]
        [ERMS] #Cyan
        [FFU ILS]
        [FBS]
        [CULR]
        [KPI/Webtrekk] #Cyan
        [VIP]
        [SAOU]
    }
}

@enduml
