@startuml
'header SayHello
'footer Page %page% of %lastpage%

skinparam component {
    backgroundColor [Biblio] LightGray
}


    package "Den Åbne Platform" {
    together {
      [Cms]
      [Search]
      [Libraries]
      [Recommend]
      [Status]
      [Suggester]
      [Itemholdings]
    }
    }
@enduml
