@startuml						
title   Material List flow
						
' Skinparams '						
skinparam monochrome true						
'skinparam handwritten true						


boundary "DDB CMS"
boundary "oAuth"
boundary "Adgangsplatform"
database "Material list"

note left of oAuth : auth.dbc.dk
note right of Adgangsplatform : login.bib.dk

"DDB CMS" -> "oAuth" : Client_id
"oAuth" --> "DDB CMS" : ClientToken

"DDB CMS" -> "Adgangsplatform" : CPR
"Adgangsplatform" --> "DDB CMS": UserToken + GUID

"DDB CMS" -> "Material list" : UserToken + GUID (+ listId)
"Material list" -> "Adgangsplatform" : UserToken
"Adgangsplatform" --> "Material list" : OK 
"Material list" --> "DDB CMS" : List

@enduml
