@startuml

title Cover Service components

package "Front End" {
    component [DDB CMS\n/ APP] as CLIENT
}

node "Cover Service" as CoverService {
    interface COVER
    [Reference Table] as refMetaDB
    [Source Table] as souMetaDB
    [Batch upload] as UBAT
} 

database "CoverDB" {
    [Stored images]
}

database "Vendor Data" {
    [File list]
}

CLIENT -> COVER
COVER -> refMetaDB
refMetaDB -> [Stored images]

UBAT -down- [File list]
UBAT -left-> [souMetaDB]
UBAT -up-> refMetaDB
UBAT -up-> [Stored images]

@enduml
