@startuml

title "DDB Cover service - Upload - usecase diagram"

left to right direction
skinparam packageStyle rectangle

actor "Medarbejder \n på et bibliotek" as medarbejder
actor "Platform /cover" <<application>> as cover
actor "Platform /search" <<application>> as search
actor "Medarbejder PC" <<device>> as computer
actor "DDB CMS /user" <<application>> as login

rectangle "Upload materialeforside" {


    :medarbejder: --> (1. Log ind)
    (1. Log ind) <-- :login:
   
    :medarbejder: --> (3. Hent billeder)
    (Godkend opløsning) <-- :cover:
    (3. Hent billeder) <-- :computer:
    (Godkend opløsning) .> (3. Hent billeder) : extends
    :medarbejder: --> (2. Fremsøg materiale \n fx pid eller faust )
    
    :medarbejder: --> (4. Verificer match)
    (4. Verificer match) .> (Hent metadata) : include
    (Hent metadata) <-- :search:

    :medarbejder: --> (5. Upload)
    (5. Upload) <-- :cover:
}

@enduml
