@startuml
title Subscription Service - Material list - Add item

' Removing color and border from cards
skinparam monochrome true

' Participants
boundary DDBCMS     as "DDB CMS"
boundary MatList    as "Material\nList"
database SubService as "Subscription"

group Add item to list

    DDBCMS->MatList: Add item to list
    
    MatList->SubService: Has accepted?
    'MatList	<--	SubService: TRUE/FALSE
    alt FALSE: Not accepted yet
        MatList	->	SubService: Create subscription
        MatList	<--	SubService: Subscription created
    end
    MatList	->	MatList: List exists?
    alt FALSE
        MatList	->	MatList: Create list
    end
    MatList	->	MatList: Add item to list
    DDBCMS	<--	MatList: Return list
end

@enduml
