@startuml
title Create patron DFD - Sequence Diagram
header After Simon Holt: Brugeroprettelse DFD
caption DDB CMS create patron (Adgangsplatformen)

' Skinparams '
skinparam monochrome true
autonumber


actor "Patron" as USER
boundary CMS
boundary Accessplatform as AP
boundary NemId as NEMID
'control "Shopping Cart" as SC
database "Session" as SESSION
database "Drupal" as DRUPAL
boundary LMS
'"Library\nManagemt\nSystem" as LMS


group Basic login

    USER -> CMS: Create patron account
    CMS -> AP: Elevated Client Id + Agency
    AP -> NEMID: Identify
    NEMID -> USER: Login
    NEMID <-- USER: NemId id + key
    AP <-- NEMID: CPR
    CMS <-- AP: Authorization code
end


    CMS -> USER: Mandatory: Name, email, pickup library, Pin (x digits)
    note right
        Name should be delivered by the Serviceplatform!
    end note
    CMS <-- USER: Name, email, pickup library, Pin (x digits)
    note right
        No of digits in PIN is variable. Standard: 4 (Aakb: 5)
    end note

group Create Patron in LMS
    CMS -> LMS: CPR, Name, email, pickup library, Pin (x digits)
    CMS <-- LMS: LMS patron data
end
group Reauthenticate Patron in LMS
    CMS -> LMS: (Preauth) CPR, Agency
    CMS <-- LMS: LMS Patron Data
end

CMS -> SESSION: Save session: Userid, LMS Patron Data
CMS -> DRUPAL: Save patron: Userid (hashed), LMS Patron Data (Name, email, blockings)

@enduml
